[package]
name = "simple-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
simple-abi = { path = "../simple-abi" }
wasm-plugins = { path = "../../lib", features = ["wasmer"] }

bincode = "^1.3"
