[package]
name = "host-func-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
host-func-abi = { path = "../host-func-abi" }
wasm-plugins = { path = "../../lib", features = ["wasmer"] }

bincode = "^1.3"
